import { useEffect, useState, type FormEvent, type ReactNode } from 'react'; import { motion } from 'framer-motion'; import { CalendarDays, MapPin, Phone, Heart, Music2, Send, Check, X, Camera } from 'lucide-react'; import { weddingData } from '../data/weddingData'; import { Carousel } from './Carousel'
const Fade=({children, className='' }:{children:ReactNode,className?:string})=><motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.65}}>{children}</motion.div>
export function Invitation(){return <section id="invitation" className="ivory invitation"><Fade><div className="ganesh">ॐ</div><p className="eyebrow">{weddingData.families}</p><p className="invite-word">Invite</p><h2>{weddingData.couple.groom} <i>&amp;</i> {weddingData.couple.bride}</h2><p className="body-copy">request the honour of your presence as they begin their forever, surrounded by music, colour and the people they love.</p><div className="gold-rule"/></Fade></section>}
export function DateReveal(){const [open,setOpen]=useState(false);return <section className="date-reveal"><Fade><p className="eyebrow">Save the moment</p><h2>A date to hold close</h2><button className="ornate-button" onClick={()=>setOpen(!open)} aria-expanded={open}>{open ? weddingData.couple.date : 'Reveal the Date'}</button>{open&&<p className="revealed">We cannot wait to celebrate with you.</p>}</Fade></section>}
export function Functions(){return <section className="functions" id="celebrations"><Fade><p className="eyebrow gold">The celebrations</p><h2>Two days, a lifetime of memories</h2><div className="event-grid">{weddingData.events.map((e,i)=><article className="event-card" key={e.name}><span>0{i+1}</span><h3>{e.name}</h3><p>{e.date} · {e.time}</p><small>{e.note}</small></article>)}</div></Fade></section>}
export function Couple(){return <section className="ivory couple"><Fade className="couple-copy"><p className="eyebrow">Our little story</p><h2>Two hearts, <em>one home.</em></h2><p className="body-copy">From everyday conversations to a beautiful forever, our story has always felt like the most natural kind of magic.</p></Fade><Fade><Carousel images={weddingData.gallery}/></Fade></section>}
export function Instagram(){return <section className="hashtag"><Fade><Camera size={27}/><p className="eyebrow">Share the joy</p><h2>{weddingData.hashtag}</h2><p>Tag your moments so we can relive every smile, dance and little detail together.</p></Fade></section>}
export function Video(){return <section className="video-section"><Fade><p className="eyebrow">A small preview</p><h2>Before the vows</h2><div className="video-frame"><iframe src={weddingData.videoUrl} title="Pre-wedding film" loading="lazy" allowFullScreen/></div></Fade></section>}
export function Countdown(){const target=+new Date(weddingData.couple.timestamp); const calc=()=>{let d=Math.max(0,target-Date.now());return [Math.floor(d/864e5),Math.floor(d/36e5)%24,Math.floor(d/6e4)%60,Math.floor(d/1e3)%60]};const [left,setLeft]=useState(calc);useEffect(()=>{const i=setInterval(()=>setLeft(calc()),1000);return()=>clearInterval(i)},[]);return <section className="countdown"><Fade><p className="eyebrow gold">Counting down</p><h2>Until we say “I do”</h2><div className="timer">{left.map((x,i)=><div key={i}><b>{String(x).padStart(2,'0')}</b><span>{['Days','Hours','Minutes','Seconds'][i]}</span></div>)}</div></Fade></section>}
export function Things(){return <section className="ivory things"><Fade><p className="eyebrow">A few details</p><h2>Things to know</h2><div className="detail-grid"><article><MapPin/><h3>Venue</h3><p>{weddingData.venue}</p></article><article><Phone/><h3>Need a hand?</h3><a href={`tel:${weddingData.contact.replace(/\s/g,'')}`}>{weddingData.contact}</a></article><article><CalendarDays/><h3>A gentle reminder</h3><p>Bring your brightest festive spirit. Traditional attire is warmly encouraged.</p></article></div></Fade></section>}
export function RSVP(){const [choice,setChoice]=useState<'yes'|'no'|null>(null),[sent,setSent]=useState(false),[error,setError]=useState(''); const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!String(f.get('name')).trim()){setError('Please share your name.');return}setSent(true)};return <section className="rsvp" id="rsvp"><Fade><p className="eyebrow gold">Kindly respond</p><h2>Will you join us?</h2>{sent?<p className="thanks"><Check/> Thank you — your reply has been received.</p>:<><div className="answer"><button className={choice==='yes'?'selected':''} onClick={()=>setChoice('yes')}><Heart/> With joy</button><button className={choice==='no'?'selected':''} onClick={()=>setChoice('no')}><X/> Regretfully</button></div>{choice&&<form onSubmit={submit} noValidate><label>Your name<input name="name" aria-describedby="rsvp-error" required/></label><label>Email address<input name="email" type="email" required/></label><label>Message <textarea name="note" rows={3}/></label>{error&&<p id="rsvp-error" role="alert">{error}</p>}<button className="ornate-button" type="submit">Send RSVP <Send size={15}/></button></form>}</>}</Fade></section>}
export function Wishes(){const [wishes,setWishes]=useState<string[]>(()=>JSON.parse(localStorage.getItem('yw-wishes')||'[]'));const [value,setValue]=useState('');const add=(e:FormEvent)=>{e.preventDefault();if(!value.trim())return;const next=[value.trim(),...wishes].slice(0,12);setWishes(next);localStorage.setItem('yw-wishes',JSON.stringify(next));setValue('')};return <section className="wishes"><Fade><p className="eyebrow">Leave a little love</p><h2>Wishes for the couple</h2><form className="wish-form" onSubmit={add}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Write a wish..." aria-label="Your wedding wish"/><button aria-label="Add wish"><Send size={17}/></button></form><div className="wish-list">{wishes.length? wishes.map((w,i)=><p key={i}>“{w}”</p>):<p className="empty">Be the first to leave a wish.</p>}</div></Fade></section>}
export function MusicPlayer(){const [on,setOn]=useState(false);return <button className="music" onClick={()=>setOn(!on)} aria-label={on?'Pause ambient music':'Play ambient music'} aria-pressed={on}><Music2 size={18}/><span>{on?'Playing':'Music'}</span></button>}
export function Footer(){return <footer><div className="ganesh">ॐ</div><h2>Yash <i>&amp;</i> Pranshu</h2><p>09 December 2026</p><p className="footer-note">Made with love, for a celebration made of love.</p></footer>}
